alias: Bilresa Wheel Changes E-Ink Page
description: Change ESPHome e-ink display page using IKEA Bilresa action_level
mode: single
max_exceeded: silent

trigger:
  - platform: mqtt
    topic: zigbee2mqtt/YOUR_BILRESA_NAME

condition:
  - condition: template
    value_template: >
      {{ trigger.payload_json.action_level is defined }}

action:
  - variables:
      new_level: "{{ trigger.payload_json.action_level | int }}"
      old_level: "{{ states('input_number.bilresa_last_action_level') | int }}"
      screen_selector: select.YOUR_ESPHOME_SCREEN_SELECTOR

  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ new_level > old_level }}
        sequence:
          - service: select.select_next
            target:
              entity_id: "{{ screen_selector }}"
            data:
              cycle: true

      - conditions:
          - condition: template
            value_template: >
              {{ new_level < old_level }}
        sequence:
          - service: select.select_previous
            target:
              entity_id: "{{ screen_selector }}"
            data:
              cycle: true

  - delay:
      milliseconds: 500

  - service: input_number.set_value
    target:
      entity_id: input_number.bilresa_last_action_level
    data:
      value: "{{ new_level }}"
